AllCops:
  Exclude:
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "db/**/*"

inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
